# --- User's custom definitions
USE_SLIC:=1
# ---

MAXCOMPILER_QUOTE   := $(shell printf %q "$(MAXCOMPILERDIR)")

RUNRULE_ARGS        := 
RUNRULE_RUNENV      := LD_LIBRARY_PATH="$(MAXELEROSDIR)/lib:$(LD_LIBRARY_PATH)" 
RUNRULE_MAXFILES    := SimpleControlledInput.max  
RUNRULE_MAXFILES_H  := SimpleControlledInput.h 
RUNRULE_CFLAGS      := 
RUNRULE_LDFLAGS     := 

TARGET_EXEC         := SimpleControlledInput
TARGET_LIBRARY      := 


